### ISSUE TITLE
No need for FormattableString in OrderBy

### ISSUE THREAD

**Issue by natilivni** [Drizin/DapperQueryBuilder#21]
Hi, in the IWhereBuilder, in the `IOrderByBuilder OrderBy(FormattableString orderBy);` method, there is no need to receive a FormattableString since order by never receives parameters.  if you change it to `IOrderByBuilder OrderBy(string orderBy);`, we would not need to add ':raw' suffixes when building a dynamic orderby clause.

**Comment by Drizin** [comment]
I understand your point but honestly I think it would be a bad change since the methods would be inconsistent - currently all methods only take `FormattableString` (never `string`) to avoid misuse (injections). 

One of the major architecture decisions in this library is that we always take `FormattableString` to be consistent and to let users explicitly define when they are interpolating something that should be taken as a raw string instead of a parameter.

If we went into this route, `.Select()` also usually takes a single string (name of column), so I would have two overloads (`string` and `FormattableString`) - that would cause overload resolutions problems, which are tricky to resolve, and frequently unsafe. Forcing everyone to use `FormattableString` (where by default embedded strings are safe) seems like a better alternative to me.
