### ISSUE TITLE
Unit Testing for IFromBuilder

### ISSUE THREAD

**Issue by bhanu7755** [Drizin/DapperQueryBuilder#37]
I'm trying to write a unit test case for my repository method and I'm just getting error which is quite an issue.

All I'm saying is 

```
IEnumerable<AppUserPersistent>? appUser = new List<AppUserPersistent>() { fixture.Create<AppUserPersistent>() };
_testUnitWork
               .Setup(x => x.UserRepository.GetListByFluentBuilderAsync(It.IsAny<IFromBuilder>()))
               .ReturnsAsync(appUser);
```
I'm getting below error 

 IRepository<AppUserPersistent> ... => ....GetListByFluentBuilderAsync(It.IsAny<IFromBuilder>()):
         This setup was not matched.

My repository method

 public Task<IEnumerable<TEntity>> GetListByFluentBuilderAsync(IFromBuilder? builder)
        {
            return builder.QueryAsync<TEntity>(_transaction);
        }

Could you please let me know what's wrong with above code

**Comment by Drizin** [comment]
By the error message looks like Moq cannot find the right method overload to mock.
I suppose it may be because of the nullable in appUser.
Your method returns `IEnumerable`, and you're trying to return `Nullable<IEnumerable<AppUserPersistent>>` - C# (or Moq) can't cast it automatically. If you remove the `?` I think it should work.

![image](https://user-images.githubusercontent.com/6320772/154500773-f8cac06f-c0cc-4c63-bafc-c544b6edec3f.png)

Let me know how it goes.

Coffee campaign:🥤 If your company is using my opensource libraries and want to show appreciation please [consider buying me a coffee](https://github.com/sponsors/Drizin?frequency=one-time)

**Comment by bhanu7755** [comment]
Thanks for the reply. Yes, I fixed it now. The issue is with type we are passing to my GetListByFluentBuilderAsync. I fixed as below now.

![image](https://user-images.githubusercontent.com/15000943/154632950-b698d41c-8f91-47f4-90b8-d2a7651cd264.png)
